name: custom-model-hol
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - joblib==1.2.0
  - snowflake-snowpark-python==1.14.0
  - snowflake-ml-python==1.4.0
  - scipy==1.11.4
  - pycaret==3.0.2
  - notebook==7.0.8
